# Generated by Django 4.2.5 on 2026-08-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ct", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="file_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="store",
            name="file_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="is_file",
            field=models.BooleanField(default=False),
        ),
    ]
